# Generated by Django 4.2.1 on 2023-06-01 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=10)),
                ('licencia', models.CharField(max_length=20)),
                ('fecha_emision_licencia', models.DateField()),
                ('titulo', models.CharField(max_length=100)),
                ('e_provincia', models.CharField(max_length=15)),
                ('e_pais', models.CharField(max_length=15)),
                ('validacion', models.BooleanField(default=False)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('contenido', models.TextField()),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.CharField(max_length=50)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('imagen', models.ImageField(upload_to='recetas/')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.profesional')),
            ],
        ),
    ]
