# Generated by Django 4.2.1 on 2023-06-01 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_profesional_receta'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profesional',
            new_name='Nutricionista',
        ),
        migrations.DeleteModel(
            name='Receta',
        ),
    ]
