# Generated by Django 4.2.1 on 2023-06-01 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_rename_profesional_nutricionista_delete_receta'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicacionReceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('contenido', models.TextField()),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Nutricionista',
            new_name='Profesional',
        ),
    ]
